### ISSUE TITLE
How to deserialize a list?

### ISSUE THREAD

**Issue by jefrajames** [americanexpress/nodes#100] opened 2019-10-30 17:13 UTC
I've tried to run simple GraphQL query returning a list:
`query { allTeams { name } }`
Here is the DTO class that I use to build a GraphQLRequestEntity:

```
@GraphQLProperty(name = "allTeams")
public class AllTeamsQuery {
    String name;
    @GraphQLIgnore
    @GraphQLProperty(name="allTeams")
    List<TeamQuery> allTeams;
    ... getters and setters
```

The GraphQL query is good and run successfully against the server. However the result is not deserialized properly: _Cannot deserialize instance of `io.superherosample.model.AllTeamsQuery` out of START_ARRAY token_ which seems to be a Jackson problem.

I guess ST is wrong in my DTO class. I've tried many options and I'm totally blocked. It would be nice that the documentation provides some examples on how to fetch lists.

**Comment by chemdrew** [comment] 2019-10-31 03:18
duplicate of #26

**Comment by jefrajames** [comment] 2019-10-31 14:50
Thanks it works! It would help a lot to have an example on how to get a list in the documentation.

**Closed as completed** 2019-11-06 17:03 UTC
