### ISSUE TITLE
Add extensions and path to error.java 

### ISSUE THREAD

**Issue by bpillai** [americanexpress/nodes#61] opened 2018-12-19 22:43 UTC
According to the graph ql spec , the error object follows the following format . 
https://facebook.github.io/graphql/June2018/#sec-Errors

{
  "errors": [
    {
      "message": "Name for character with ID 1002 could not be fetched.",
      "locations": [ { "line": 6, "column": 7 } ],
      "path": [ "hero", "heroFriends", 1, "name" ],
      "extensions": {
        "code": "CAN_NOT_FETCH_BY_ID",
        "timestamp": "Fri Feb 9 14:33:09 UTC 2018"
      }
    }
  ]
}

**Comment by chemdrew** [comment] 2019-01-20 16:17
Hi @bpillai closing this as a duplicate of #22 
Unfortunately I have not had the time to implement this yet but would be more than happy to accept a PR for it!

**Closed by chemdrew** 2019-01-20 16:17 UTC
