### ISSUE TITLE
StackOverflowError when model class has property with reference on himself 

### ISSUE THREAD

**Issue by arudnev84** [americanexpress/nodes#82] opened 2019-07-10 13:37 UTC
public class DisplayElement {
    private String type;
    private String text;
    private List<String> styles;
    private String url;
    **private List< DisplayElement > displayElements;**
    private Boolean isSelected;
    private Boolean isHighlighted;
}

**Comment by chemdrew** [comment] 2019-07-13 23:06
closing as duplicate of #79

**Closed by chemdrew** 2019-07-13 23:06 UTC
Labels: duplicate
